// <auto-generated />
using System;
using Backend.Repository.MySQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Backend.Migrations
{
    [DbContext(typeof(HealthClinicDbContext))]
    [Migration("20201120185620_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Backend.Model.BlogAndNotification.PatientFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsForPublishing")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<DateTime>("PublishingDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Text")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("PatientID");

                    b.ToTable("PatientFeedbacks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAnonymous = false,
                            IsForPublishing = true,
                            IsPublished = true,
                            PatientID = 1,
                            PublishingDate = new DateTime(2020, 10, 30, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Text = "Iako rečenica nema značenje, ona ima dugu istoriju. Nju su nekoliko vekova koristili tipografi da bi prikazali najistaknutije osobine svojih fontova. Koristi se zbog toga što slova koja su uključena u nju, kao i razmak između slova u tim kombinacijama na najbolji mogući način otkrivaju težinu, dizajn i druge važne funkcije slovnog oblika."
                        },
                        new
                        {
                            Id = 2,
                            IsAnonymous = true,
                            IsForPublishing = true,
                            IsPublished = true,
                            PatientID = 2,
                            PublishingDate = new DateTime(2020, 8, 15, 9, 17, 0, 0, DateTimeKind.Unspecified),
                            Text = "Iako rečenica nema značenje, ona ima dugu istoriju. Nju su nekoliko vekova koristili tipografi da bi prikazali najistaknutije osobine svojih fontova. Koristi se zbog toga što slova koja su uključena u nju, kao i razmak između slova u tim kombinacijama na najbolji mogući način otkrivaju težinu, dizajn i druge važne funkcije slovnog oblika."
                        },
                        new
                        {
                            Id = 3,
                            IsAnonymous = true,
                            IsForPublishing = true,
                            IsPublished = false,
                            PatientID = 3,
                            PublishingDate = new DateTime(2020, 9, 3, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            Text = "Iako rečenica nema značenje, ona ima dugu istoriju. Nju su nekoliko vekova koristili tipografi da bi prikazali najistaknutije osobine svojih fontova. Koristi se zbog toga što slova koja su uključena u nju, kao i razmak između slova u tim kombinacijama na najbolji mogući način otkrivaju težinu, dizajn i druge važne funkcije slovnog oblika."
                        },
                        new
                        {
                            Id = 4,
                            IsAnonymous = false,
                            IsForPublishing = false,
                            IsPublished = false,
                            PatientID = 4,
                            PublishingDate = new DateTime(2020, 11, 6, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            Text = "Iako rečenica nema značenje, ona ima dugu istoriju. Nju su nekoliko vekova koristili tipografi da bi prikazali najistaknutije osobine svojih fontova. Koristi se zbog toga što slova koja su uključena u nju, kao i razmak između slova u tim kombinacijama na najbolji mogući način otkrivaju težinu, dizajn i druge važne funkcije slovnog oblika."
                        },
                        new
                        {
                            Id = 5,
                            IsAnonymous = false,
                            IsForPublishing = false,
                            IsPublished = false,
                            PatientID = 2,
                            PublishingDate = new DateTime(2020, 10, 18, 7, 30, 0, 0, DateTimeKind.Unspecified),
                            Text = "Iako rečenica nema značenje, ona ima dugu istoriju. Nju su nekoliko vekova koristili tipografi da bi prikazali najistaknutije osobine svojih fontova. Koristi se zbog toga što slova koja su uključena u nju, kao i razmak između slova u tim kombinacijama na najbolji mogući način otkrivaju težinu, dizajn i druge važne funkcije slovnog oblika."
                        },
                        new
                        {
                            Id = 6,
                            IsAnonymous = true,
                            IsForPublishing = true,
                            IsPublished = false,
                            PatientID = 4,
                            PublishingDate = new DateTime(2020, 10, 15, 6, 30, 0, 0, DateTimeKind.Unspecified),
                            Text = "Iako rečenica nema značenje, ona ima dugu istoriju. Nju su nekoliko vekova koristili tipografi da bi prikazali najistaknutije osobine svojih fontova. Koristi se zbog toga što slova koja su uključena u nju, kao i razmak između slova u tim kombinacijama na najbolji mogući način otkrivaju težinu, dizajn i druge važne funkcije slovnog oblika."
                        });
                });

            modelBuilder.Entity("Backend.Model.PatientDoctor.MedicalExaminationReport", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("PublishingDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("medicalExaminationID")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("medicalExaminationID");

                    b.ToTable("MedicalExaminationReport");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Comment = "Pacijent je dobro i nema većih problema",
                            PublishingDate = new DateTime(2020, 10, 30, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            medicalExaminationID = 1
                        },
                        new
                        {
                            id = 2,
                            Comment = "Pacijent je veoma dobro i nema većih problema",
                            PublishingDate = new DateTime(2020, 10, 30, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            medicalExaminationID = 2
                        },
                        new
                        {
                            id = 3,
                            Comment = "Pacijent ima virus",
                            PublishingDate = new DateTime(2020, 10, 30, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            medicalExaminationID = 3
                        });
                });

            modelBuilder.Entity("Model.AllActors.City", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Adress")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("CountryID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("PostCode")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("CountryID");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            id = 1,
                            CountryID = 1,
                            Name = "Beograd",
                            PostCode = 11000
                        });
                });

            modelBuilder.Entity("Model.AllActors.Country", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Code = "SRB",
                            Name = "Srbija"
                        });
                });

            modelBuilder.Entity("Model.AllActors.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EMail")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Jmbg")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Password")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Surname")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Username")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("cityID")
                        .HasColumnType("int");

                    b.Property<int>("specialitationID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("specialitationID");

                    b.ToTable("Doctor");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactNumber = "06345111144",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EMail = "pera@gmail.com",
                            Jmbg = "123",
                            Name = "Petar",
                            Password = "123",
                            Surname = "Petrovic",
                            Username = "pera",
                            cityID = 1,
                            specialitationID = 1
                        },
                        new
                        {
                            Id = 2,
                            ContactNumber = "06345111144",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EMail = "pera@gmail.com",
                            Jmbg = "123",
                            Name = "Petar",
                            Password = "123",
                            Surname = "Petrovic",
                            Username = "pera",
                            cityID = 1,
                            specialitationID = 1
                        },
                        new
                        {
                            Id = 3,
                            ContactNumber = "06345111144",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EMail = "pera@gmail.com",
                            Jmbg = "123",
                            Name = "Petar",
                            Password = "123",
                            Surname = "Petrovic",
                            Username = "pera",
                            cityID = 1,
                            specialitationID = 1
                        },
                        new
                        {
                            Id = 4,
                            ContactNumber = "06345111144",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EMail = "pera@gmail.com",
                            Jmbg = "123",
                            Name = "Petar",
                            Password = "123",
                            Surname = "Petrovic",
                            Username = "pera",
                            cityID = 1,
                            specialitationID = 1
                        });
                });

            modelBuilder.Entity("Model.AllActors.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EMail")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("GuestAccount")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Jmbg")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("MedicalRecordID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Password")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Surname")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Username")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("cityID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Patient");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactNumber = "063555333",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EMail = "pera@gmail.com",
                            GuestAccount = false,
                            Jmbg = "123",
                            MedicalRecordID = 1,
                            Name = "Petar",
                            Password = "123",
                            Surname = "Petrovic",
                            Username = "pera",
                            cityID = 1
                        },
                        new
                        {
                            Id = 2,
                            ContactNumber = "063555333",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EMail = "pera@gmail.com",
                            GuestAccount = false,
                            Jmbg = "123",
                            MedicalRecordID = 2,
                            Name = "Milos",
                            Password = "123",
                            Surname = "Mitrovic",
                            Username = "pera",
                            cityID = 1
                        },
                        new
                        {
                            Id = 3,
                            ContactNumber = "063555333",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EMail = "pera@gmail.com",
                            GuestAccount = false,
                            Jmbg = "123",
                            MedicalRecordID = 3,
                            Name = "Jovan",
                            Password = "123",
                            Surname = "Jovanovic",
                            Username = "pera",
                            cityID = 1
                        },
                        new
                        {
                            Id = 4,
                            ContactNumber = "063555333",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EMail = "pera@gmail.com",
                            GuestAccount = false,
                            Jmbg = "123",
                            MedicalRecordID = 4,
                            Name = "Milica",
                            Password = "123",
                            Surname = "Micic",
                            Username = "pera",
                            cityID = 1
                        });
                });

            modelBuilder.Entity("Model.Doctor.Specialitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("SpecialitationForDoctor")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Specialitations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SpecialitationForDoctor = "Hirurg"
                        });
                });

            modelBuilder.Entity("Model.DoctorMenager.Medicament", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Ingredients")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Producer")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("StateOfValidation")
                        .HasColumnType("int");

                    b.Property<int>("medicalRecordID")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("medicalRecordID");

                    b.ToTable("Medicaments");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Code = "L123",
                            Ingredients = "sastojak1, sastojak2, sastojak3",
                            Name = "Brufen",
                            Producer = "Hemofarm",
                            Quantity = 10,
                            StateOfValidation = 0,
                            medicalRecordID = 1
                        },
                        new
                        {
                            id = 2,
                            Code = "L233",
                            Ingredients = "sastojak1, sastojak2, sastojak3",
                            Name = "Brufen",
                            Producer = "Hemofarm",
                            Quantity = 10,
                            StateOfValidation = 0,
                            medicalRecordID = 2
                        },
                        new
                        {
                            id = 3,
                            Code = "L523",
                            Ingredients = "sastojak1, sastojak2, sastojak3",
                            Name = "Brufen",
                            Producer = "Hemofarm",
                            Quantity = 10,
                            StateOfValidation = 0,
                            medicalRecordID = 3
                        },
                        new
                        {
                            id = 4,
                            Code = "L423",
                            Ingredients = "sastojak1, sastojak2, sastojak3",
                            Name = "Brufen",
                            Producer = "Hemofarm",
                            Quantity = 10,
                            StateOfValidation = 0,
                            medicalRecordID = 4
                        },
                        new
                        {
                            id = 5,
                            Code = "L423",
                            Ingredients = "sastojak1, sastojak2, sastojak3",
                            Name = "Brufen",
                            Producer = "Hemofarm",
                            Quantity = 10,
                            StateOfValidation = 0,
                            medicalRecordID = 2
                        },
                        new
                        {
                            id = 6,
                            Code = "L423",
                            Ingredients = "sastojak1, sastojak2, sastojak3",
                            Name = "Brufen",
                            Producer = "Hemofarm",
                            Quantity = 10,
                            StateOfValidation = 0,
                            medicalRecordID = 1
                        },
                        new
                        {
                            id = 7,
                            Code = "L423",
                            Ingredients = "sastojak1, sastojak2, sastojak3",
                            Name = "Brufen",
                            Producer = "Hemofarm",
                            Quantity = 10,
                            StateOfValidation = 0,
                            medicalRecordID = 1
                        });
                });

            modelBuilder.Entity("Model.Manager.InventaryRoom", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("roomID")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("roomID");

                    b.ToTable("InventaryRoom");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Name = "Stolovi",
                            Quantity = 1,
                            roomID = 1
                        },
                        new
                        {
                            id = 2,
                            Name = "Stolice",
                            Quantity = 1,
                            roomID = 1
                        },
                        new
                        {
                            id = 3,
                            Name = "Kreveti",
                            Quantity = 1,
                            roomID = 2
                        });
                });

            modelBuilder.Entity("Model.Patient.Question", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Answer")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("answerID")
                        .HasColumnType("int");

                    b.Property<int>("surveyID")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("surveyID");

                    b.ToTable("Question");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Answer = 0,
                            QuestionText = "Pitanje1",
                            answerID = 1,
                            surveyID = 1
                        },
                        new
                        {
                            id = 2,
                            Answer = 0,
                            QuestionText = "Pitanje2",
                            answerID = 1,
                            surveyID = 1
                        },
                        new
                        {
                            id = 3,
                            Answer = 0,
                            QuestionText = "Pitanje3",
                            answerID = 1,
                            surveyID = 2
                        },
                        new
                        {
                            id = 4,
                            Answer = 0,
                            QuestionText = "Pitanje4",
                            answerID = 1,
                            surveyID = 2
                        },
                        new
                        {
                            id = 5,
                            Answer = 0,
                            QuestionText = "Pitanje5",
                            answerID = 1,
                            surveyID = 1
                        });
                });

            modelBuilder.Entity("Model.Patient.Survey", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CommentSurvey")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("PublishingDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("medicalExaminationID")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("medicalExaminationID");

                    b.ToTable("Survey1");

                    b.HasData(
                        new
                        {
                            id = 1,
                            CommentSurvey = "Sve je super u bolnici",
                            PublishingDate = new DateTime(2020, 11, 6, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "Naslov",
                            medicalExaminationID = 1
                        },
                        new
                        {
                            id = 2,
                            CommentSurvey = "Sve je super u bolnici",
                            PublishingDate = new DateTime(2020, 11, 6, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "Naslov",
                            medicalExaminationID = 2
                        });
                });

            modelBuilder.Entity("Model.PatientDoctor.Allergies", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("medicalRecordID")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("medicalRecordID");

                    b.ToTable("Allergies");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Name = "Penicilin",
                            medicalRecordID = 1
                        },
                        new
                        {
                            id = 2,
                            Name = "Penicilin",
                            medicalRecordID = 3
                        },
                        new
                        {
                            id = 3,
                            Name = "Penicilin",
                            medicalRecordID = 2
                        },
                        new
                        {
                            id = 4,
                            Name = "Penicilin",
                            medicalRecordID = 1
                        });
                });

            modelBuilder.Entity("Model.PatientDoctor.Anamnesis", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("id");

                    b.ToTable("Anamnesies");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Description = "Pacijent je dobro"
                        },
                        new
                        {
                            id = 2,
                            Description = "Pacijent je loše"
                        },
                        new
                        {
                            id = 3,
                            Description = "Pacijent je vrlo dobro"
                        });
                });

            modelBuilder.Entity("Model.PatientDoctor.Diagnosis", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("anamnesisID")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("anamnesisID");

                    b.ToTable("Diagnosies");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Name = "Prehlada",
                            anamnesisID = 1
                        },
                        new
                        {
                            id = 2,
                            Name = "Virus",
                            anamnesisID = 2
                        },
                        new
                        {
                            id = 3,
                            Name = "Migrena",
                            anamnesisID = 2
                        });
                });

            modelBuilder.Entity("Model.PatientDoctor.MedicalRecord", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<int>("anamnesisID")
                        .HasColumnType("int");

                    b.Property<int>("patientID")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("anamnesisID");

                    b.ToTable("MedicalRecords");

                    b.HasData(
                        new
                        {
                            id = 1,
                            anamnesisID = 1,
                            patientID = 1
                        },
                        new
                        {
                            id = 2,
                            anamnesisID = 1,
                            patientID = 2
                        },
                        new
                        {
                            id = 3,
                            anamnesisID = 1,
                            patientID = 3
                        },
                        new
                        {
                            id = 4,
                            anamnesisID = 1,
                            patientID = 4
                        });
                });

            modelBuilder.Entity("Model.PatientDoctor.Symptoms", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("anamnesisID")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("anamnesisID");

                    b.ToTable("Symptomes");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Name = "Temperatura",
                            anamnesisID = 2
                        },
                        new
                        {
                            id = 2,
                            Name = "Kašalj",
                            anamnesisID = 1
                        },
                        new
                        {
                            id = 3,
                            Name = "Glavobolja",
                            anamnesisID = 2
                        });
                });

            modelBuilder.Entity("Model.Term.MedicalExamination", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("FromDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("ToDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Urgency")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("doctorID")
                        .HasColumnType("int");

                    b.Property<int>("patientID")
                        .HasColumnType("int");

                    b.Property<int>("roomID")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("doctorID");

                    b.HasIndex("patientID");

                    b.HasIndex("roomID");

                    b.ToTable("MedicalExamination");

                    b.HasData(
                        new
                        {
                            id = 1,
                            FromDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "Sve je bilo uredu na pregledu",
                            ToDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Urgency = false,
                            doctorID = 1,
                            patientID = 2,
                            roomID = 1
                        },
                        new
                        {
                            id = 2,
                            FromDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "Sve je bilo uredu na pregledu",
                            ToDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Urgency = false,
                            doctorID = 2,
                            patientID = 1,
                            roomID = 2
                        },
                        new
                        {
                            id = 3,
                            FromDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "Sve je bilo uredu na pregledu",
                            ToDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Urgency = false,
                            doctorID = 2,
                            patientID = 3,
                            roomID = 3
                        });
                });

            modelBuilder.Entity("Model.Term.Room", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("FromDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RoomID")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("ToDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("typeOfRoomID")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("typeOfRoomID");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            id = 1,
                            FromDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomID = "101",
                            ToDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            typeOfRoomID = 1
                        },
                        new
                        {
                            id = 2,
                            FromDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomID = "201",
                            ToDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            typeOfRoomID = 1
                        },
                        new
                        {
                            id = 3,
                            FromDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomID = "301",
                            ToDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            typeOfRoomID = 1
                        });
                });

            modelBuilder.Entity("Model.Term.Surgery", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("FromDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("ToDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Urgency")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("doctorSpecialistID")
                        .HasColumnType("int");

                    b.Property<int>("patientID")
                        .HasColumnType("int");

                    b.Property<int>("roomID")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("doctorSpecialistID");

                    b.HasIndex("patientID");

                    b.HasIndex("roomID");

                    b.ToTable("Survey");
                });

            modelBuilder.Entity("Model.Term.TypeOfRoom", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NameOfType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("id");

                    b.ToTable("TypesOfRoom");

                    b.HasData(
                        new
                        {
                            id = 1,
                            NameOfType = "Soba za preglede"
                        },
                        new
                        {
                            id = 2,
                            NameOfType = "Soba za operacije"
                        });
                });

            modelBuilder.Entity("Backend.Model.BlogAndNotification.PatientFeedback", b =>
                {
                    b.HasOne("Model.AllActors.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Model.PatientDoctor.MedicalExaminationReport", b =>
                {
                    b.HasOne("Model.Term.MedicalExamination", "MedicalExamination")
                        .WithMany()
                        .HasForeignKey("medicalExaminationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Model.AllActors.City", b =>
                {
                    b.HasOne("Model.AllActors.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Model.AllActors.Doctor", b =>
                {
                    b.HasOne("Model.Doctor.Specialitation", "Specialitation")
                        .WithMany()
                        .HasForeignKey("specialitationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Model.DoctorMenager.Medicament", b =>
                {
                    b.HasOne("Model.PatientDoctor.MedicalRecord", "MedicalRecord")
                        .WithMany("Medicament")
                        .HasForeignKey("medicalRecordID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Model.Manager.InventaryRoom", b =>
                {
                    b.HasOne("Model.Term.Room", "Room")
                        .WithMany("Equipment")
                        .HasForeignKey("roomID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Model.Patient.Question", b =>
                {
                    b.HasOne("Model.Patient.Survey", "Survey")
                        .WithMany("Question")
                        .HasForeignKey("surveyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Model.Patient.Survey", b =>
                {
                    b.HasOne("Model.Term.MedicalExamination", "MedicalExamination")
                        .WithMany()
                        .HasForeignKey("medicalExaminationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Model.PatientDoctor.Allergies", b =>
                {
                    b.HasOne("Model.PatientDoctor.MedicalRecord", "MedicalRecord")
                        .WithMany("Allergies")
                        .HasForeignKey("medicalRecordID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Model.PatientDoctor.Diagnosis", b =>
                {
                    b.HasOne("Model.PatientDoctor.Anamnesis", "Anamnesis")
                        .WithMany("Diagnosis")
                        .HasForeignKey("anamnesisID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Model.PatientDoctor.MedicalRecord", b =>
                {
                    b.HasOne("Model.PatientDoctor.Anamnesis", "Anamnesis")
                        .WithMany()
                        .HasForeignKey("anamnesisID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.AllActors.Patient", "Patient")
                        .WithOne("MedicalRecord")
                        .HasForeignKey("Model.PatientDoctor.MedicalRecord", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Model.PatientDoctor.Symptoms", b =>
                {
                    b.HasOne("Model.PatientDoctor.Anamnesis", "Anamnesis")
                        .WithMany("Symptoms")
                        .HasForeignKey("anamnesisID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Model.Term.MedicalExamination", b =>
                {
                    b.HasOne("Model.AllActors.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("doctorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.AllActors.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("patientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Term.Room", "Room")
                        .WithMany()
                        .HasForeignKey("roomID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Model.Term.Room", b =>
                {
                    b.HasOne("Model.Term.TypeOfRoom", "TypeOfRoom")
                        .WithMany()
                        .HasForeignKey("typeOfRoomID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Model.Term.Surgery", b =>
                {
                    b.HasOne("Model.AllActors.Doctor", "DoctorSpecialist")
                        .WithMany()
                        .HasForeignKey("doctorSpecialistID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.AllActors.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("patientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Term.Room", "Room")
                        .WithMany()
                        .HasForeignKey("roomID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
