// <auto-generated />
using System;
using Backend.Repository.MySQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Backend.Migrations
{
    [DbContext(typeof(HealthClinicDbContext))]
    [Migration("20201122192559_DatabaseMigration")]
    partial class DatabaseMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Backend.Model.BlogAndNotification.PatientFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsForPublishing")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PublishingDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Text")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientFeedbacks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAnonymous = false,
                            IsForPublishing = true,
                            IsPublished = true,
                            PatientId = 1,
                            PublishingDate = new DateTime(2020, 10, 30, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Text = "Iako rečenica nema značenje, ona ima dugu istoriju. Nju su nekoliko vekova koristili tipografi da bi prikazali najistaknutije osobine svojih fontova. Koristi se zbog toga što slova koja su uključena u nju, kao i razmak između slova u tim kombinacijama na najbolji mogući način otkrivaju težinu, dizajn i druge važne funkcije slovnog oblika."
                        },
                        new
                        {
                            Id = 2,
                            IsAnonymous = true,
                            IsForPublishing = true,
                            IsPublished = true,
                            PatientId = 2,
                            PublishingDate = new DateTime(2020, 8, 15, 9, 17, 0, 0, DateTimeKind.Unspecified),
                            Text = "Iako rečenica nema značenje, ona ima dugu istoriju. Nju su nekoliko vekova koristili tipografi da bi prikazali najistaknutije osobine svojih fontova. Koristi se zbog toga što slova koja su uključena u nju, kao i razmak između slova u tim kombinacijama na najbolji mogući način otkrivaju težinu, dizajn i druge važne funkcije slovnog oblika."
                        },
                        new
                        {
                            Id = 3,
                            IsAnonymous = true,
                            IsForPublishing = true,
                            IsPublished = false,
                            PatientId = 3,
                            PublishingDate = new DateTime(2020, 9, 3, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            Text = "Iako rečenica nema značenje, ona ima dugu istoriju. Nju su nekoliko vekova koristili tipografi da bi prikazali najistaknutije osobine svojih fontova. Koristi se zbog toga što slova koja su uključena u nju, kao i razmak između slova u tim kombinacijama na najbolji mogući način otkrivaju težinu, dizajn i druge važne funkcije slovnog oblika."
                        },
                        new
                        {
                            Id = 4,
                            IsAnonymous = false,
                            IsForPublishing = false,
                            IsPublished = false,
                            PatientId = 4,
                            PublishingDate = new DateTime(2020, 11, 6, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            Text = "Iako rečenica nema značenje, ona ima dugu istoriju. Nju su nekoliko vekova koristili tipografi da bi prikazali najistaknutije osobine svojih fontova. Koristi se zbog toga što slova koja su uključena u nju, kao i razmak između slova u tim kombinacijama na najbolji mogući način otkrivaju težinu, dizajn i druge važne funkcije slovnog oblika."
                        },
                        new
                        {
                            Id = 5,
                            IsAnonymous = false,
                            IsForPublishing = false,
                            IsPublished = false,
                            PatientId = 2,
                            PublishingDate = new DateTime(2020, 10, 18, 7, 30, 0, 0, DateTimeKind.Unspecified),
                            Text = "Iako rečenica nema značenje, ona ima dugu istoriju. Nju su nekoliko vekova koristili tipografi da bi prikazali najistaknutije osobine svojih fontova. Koristi se zbog toga što slova koja su uključena u nju, kao i razmak između slova u tim kombinacijama na najbolji mogući način otkrivaju težinu, dizajn i druge važne funkcije slovnog oblika."
                        },
                        new
                        {
                            Id = 6,
                            IsAnonymous = true,
                            IsForPublishing = true,
                            IsPublished = false,
                            PatientId = 4,
                            PublishingDate = new DateTime(2020, 10, 15, 6, 30, 0, 0, DateTimeKind.Unspecified),
                            Text = "Iako rečenica nema značenje, ona ima dugu istoriju. Nju su nekoliko vekova koristili tipografi da bi prikazali najistaknutije osobine svojih fontova. Koristi se zbog toga što slova koja su uključena u nju, kao i razmak između slova u tim kombinacijama na najbolji mogući način otkrivaju težinu, dizajn i druge važne funkcije slovnog oblika."
                        });
                });

            modelBuilder.Entity("Backend.Model.PatientDoctor.MedicalExaminationReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("MedicalExaminationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PublishingDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("MedicalExaminationId");

                    b.ToTable("MedicalExaminationReport");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Pacijent je dobro i nema većih problema",
                            MedicalExaminationId = 1,
                            PublishingDate = new DateTime(2020, 10, 30, 10, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Pacijent je veoma dobro i nema većih problema",
                            MedicalExaminationId = 2,
                            PublishingDate = new DateTime(2020, 10, 30, 10, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Pacijent ima virus",
                            MedicalExaminationId = 3,
                            PublishingDate = new DateTime(2020, 10, 30, 10, 30, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Model.AllActors.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Adress")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("PostCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            Name = "Beograd",
                            PostCode = 11000
                        });
                });

            modelBuilder.Entity("Model.AllActors.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "SRB",
                            Name = "Srbija"
                        });
                });

            modelBuilder.Entity("Model.AllActors.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EMail")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Jmbg")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Password")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("SpecialitationId")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Username")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("SpecialitationId");

                    b.ToTable("Doctor");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            ContactNumber = "06345111144",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EMail = "pera@gmail.com",
                            Jmbg = "123",
                            Name = "Petar",
                            Password = "123",
                            SpecialitationId = 1,
                            Surname = "Petrovic",
                            Username = "pera"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            ContactNumber = "06345111144",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EMail = "pera@gmail.com",
                            Jmbg = "123",
                            Name = "Petar",
                            Password = "123",
                            SpecialitationId = 1,
                            Surname = "Petrovic",
                            Username = "pera"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 1,
                            ContactNumber = "06345111144",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EMail = "pera@gmail.com",
                            Jmbg = "123",
                            Name = "Petar",
                            Password = "123",
                            SpecialitationId = 1,
                            Surname = "Petrovic",
                            Username = "pera"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 1,
                            ContactNumber = "06345111144",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EMail = "pera@gmail.com",
                            Jmbg = "123",
                            Name = "Petar",
                            Password = "123",
                            SpecialitationId = 1,
                            Surname = "Petrovic",
                            Username = "pera"
                        });
                });

            modelBuilder.Entity("Model.AllActors.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EMail")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("GuestAccount")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Jmbg")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("MedicalRecordId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Password")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Surname")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Username")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Patient");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            ContactNumber = "063555333",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EMail = "pera@gmail.com",
                            GuestAccount = false,
                            Jmbg = "123",
                            MedicalRecordId = 1,
                            Name = "Petar",
                            Password = "123",
                            Surname = "Petrovic",
                            Username = "pera"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            ContactNumber = "063555333",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EMail = "pera@gmail.com",
                            GuestAccount = false,
                            Jmbg = "123",
                            MedicalRecordId = 2,
                            Name = "Milos",
                            Password = "123",
                            Surname = "Mitrovic",
                            Username = "pera"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 1,
                            ContactNumber = "063555333",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EMail = "pera@gmail.com",
                            GuestAccount = false,
                            Jmbg = "123",
                            MedicalRecordId = 3,
                            Name = "Jovan",
                            Password = "123",
                            Surname = "Jovanovic",
                            Username = "pera"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 1,
                            ContactNumber = "063555333",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EMail = "pera@gmail.com",
                            GuestAccount = false,
                            Jmbg = "123",
                            MedicalRecordId = 4,
                            Name = "Milica",
                            Password = "123",
                            Surname = "Micic",
                            Username = "pera"
                        });
                });

            modelBuilder.Entity("Model.Doctor.Specialitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("SpecialitationForDoctor")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Specialitations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SpecialitationForDoctor = "Hirurg"
                        });
                });

            modelBuilder.Entity("Model.DoctorMenager.Medicament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Ingredients")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("MedicalRecordId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Producer")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("StateOfValidation")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MedicalRecordId");

                    b.ToTable("Medicaments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "L123",
                            Ingredients = "sastojak1, sastojak2, sastojak3",
                            MedicalRecordId = 1,
                            Name = "Brufen",
                            Producer = "Hemofarm",
                            Quantity = 10,
                            StateOfValidation = 0
                        },
                        new
                        {
                            Id = 2,
                            Code = "L233",
                            Ingredients = "sastojak1, sastojak2, sastojak3",
                            MedicalRecordId = 2,
                            Name = "Brufen",
                            Producer = "Hemofarm",
                            Quantity = 10,
                            StateOfValidation = 0
                        },
                        new
                        {
                            Id = 3,
                            Code = "L523",
                            Ingredients = "sastojak1, sastojak2, sastojak3",
                            MedicalRecordId = 3,
                            Name = "Brufen",
                            Producer = "Hemofarm",
                            Quantity = 10,
                            StateOfValidation = 0
                        },
                        new
                        {
                            Id = 4,
                            Code = "L423",
                            Ingredients = "sastojak1, sastojak2, sastojak3",
                            MedicalRecordId = 4,
                            Name = "Brufen",
                            Producer = "Hemofarm",
                            Quantity = 10,
                            StateOfValidation = 0
                        },
                        new
                        {
                            Id = 5,
                            Code = "L423",
                            Ingredients = "sastojak1, sastojak2, sastojak3",
                            MedicalRecordId = 2,
                            Name = "Brufen",
                            Producer = "Hemofarm",
                            Quantity = 10,
                            StateOfValidation = 0
                        },
                        new
                        {
                            Id = 6,
                            Code = "L423",
                            Ingredients = "sastojak1, sastojak2, sastojak3",
                            MedicalRecordId = 1,
                            Name = "Brufen",
                            Producer = "Hemofarm",
                            Quantity = 10,
                            StateOfValidation = 0
                        },
                        new
                        {
                            Id = 7,
                            Code = "L423",
                            Ingredients = "sastojak1, sastojak2, sastojak3",
                            MedicalRecordId = 1,
                            Name = "Brufen",
                            Producer = "Hemofarm",
                            Quantity = 10,
                            StateOfValidation = 0
                        });
                });

            modelBuilder.Entity("Model.Manager.InventaryRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("InventaryRoom");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Stolovi",
                            Quantity = 1,
                            RoomId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Stolice",
                            Quantity = 1,
                            RoomId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Kreveti",
                            Quantity = 1,
                            RoomId = 2
                        });
                });

            modelBuilder.Entity("Model.Patient.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Answer")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("SurveyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SurveyId");

                    b.ToTable("Question");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Answer = 1,
                            QuestionText = "Ljubaznost doktora prema pacijentu",
                            SurveyId = 1
                        },
                        new
                        {
                            Id = 2,
                            Answer = 0,
                            QuestionText = "Posvećenost doktora pacijentu",
                            SurveyId = 1
                        },
                        new
                        {
                            Id = 3,
                            Answer = 1,
                            QuestionText = "Pružanje informacija od strane doktora o mom zdravstvenom stanju i mogućnostima lečenja",
                            SurveyId = 1
                        },
                        new
                        {
                            Id = 4,
                            Answer = 0,
                            QuestionText = "Ljubaznost medicinskog osoblja prema pacijentu",
                            SurveyId = 1
                        },
                        new
                        {
                            Id = 5,
                            Answer = 1,
                            QuestionText = "Posvećenost medicinskog osoblja pacijentu",
                            SurveyId = 1
                        },
                        new
                        {
                            Id = 6,
                            Answer = 0,
                            QuestionText = "Profesionalizam u obavljanju svoji duznosti medicinskog osoblja",
                            SurveyId = 1
                        },
                        new
                        {
                            Id = 7,
                            Answer = 3,
                            QuestionText = "Ispunjenost vremena zakazanog termina i vreme provedeno u cekonici",
                            SurveyId = 1
                        },
                        new
                        {
                            Id = 8,
                            Answer = 4,
                            QuestionText = "Higijena unutar bolnice",
                            SurveyId = 1
                        },
                        new
                        {
                            Id = 9,
                            Answer = 1,
                            QuestionText = "Opremljenost bolnice",
                            SurveyId = 1
                        },
                        new
                        {
                            Id = 10,
                            Answer = 1,
                            QuestionText = "Ljubaznost doktora prema pacijentu",
                            SurveyId = 2
                        },
                        new
                        {
                            Id = 11,
                            Answer = 1,
                            QuestionText = "Posvećenost doktora pacijentu",
                            SurveyId = 2
                        },
                        new
                        {
                            Id = 12,
                            Answer = 0,
                            QuestionText = "Pružanje informacija od strane doktora o mom zdravstvenom stanju i mogućnostima lečenja",
                            SurveyId = 2
                        },
                        new
                        {
                            Id = 13,
                            Answer = 3,
                            QuestionText = "Ljubaznost medicinskog osoblja prema pacijentu",
                            SurveyId = 2
                        },
                        new
                        {
                            Id = 14,
                            Answer = 4,
                            QuestionText = "Posvećenost medicinskog osoblja pacijentu",
                            SurveyId = 2
                        },
                        new
                        {
                            Id = 15,
                            Answer = 4,
                            QuestionText = "Profesionalizam u obavljanju svoji duznosti medicinskog osoblja",
                            SurveyId = 2
                        },
                        new
                        {
                            Id = 16,
                            Answer = 2,
                            QuestionText = "Ispunjenost vremena zakazanog termina i vreme provedeno u cekonici",
                            SurveyId = 2
                        },
                        new
                        {
                            Id = 17,
                            Answer = 1,
                            QuestionText = "Higijena unutar bolnice",
                            SurveyId = 2
                        },
                        new
                        {
                            Id = 18,
                            Answer = 2,
                            QuestionText = "Opremljenost bolnice",
                            SurveyId = 2
                        });
                });

            modelBuilder.Entity("Model.Patient.Survey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CommentSurvey")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("MedicalExaminationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PublishingDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("MedicalExaminationId");

                    b.ToTable("Survey1");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommentSurvey = "Sve je super u bolnici",
                            MedicalExaminationId = 1,
                            PublishingDate = new DateTime(2020, 11, 6, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "Naslov"
                        },
                        new
                        {
                            Id = 2,
                            CommentSurvey = "Sve je super u bolnici",
                            MedicalExaminationId = 2,
                            PublishingDate = new DateTime(2020, 11, 6, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "Naslov"
                        });
                });

            modelBuilder.Entity("Model.PatientDoctor.Allergies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("MedicalRecordId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("MedicalRecordId");

                    b.ToTable("Allergies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MedicalRecordId = 1,
                            Name = "Penicilin"
                        },
                        new
                        {
                            Id = 2,
                            MedicalRecordId = 3,
                            Name = "Penicilin"
                        },
                        new
                        {
                            Id = 3,
                            MedicalRecordId = 2,
                            Name = "Penicilin"
                        },
                        new
                        {
                            Id = 4,
                            MedicalRecordId = 1,
                            Name = "Penicilin"
                        });
                });

            modelBuilder.Entity("Model.PatientDoctor.Anamnesis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Anamnesies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Pacijent je dobro"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Pacijent je loše"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Pacijent je vrlo dobro"
                        });
                });

            modelBuilder.Entity("Model.PatientDoctor.Diagnosis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AnamnesisId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("AnamnesisId");

                    b.ToTable("Diagnosies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnamnesisId = 1,
                            Name = "Prehlada"
                        },
                        new
                        {
                            Id = 2,
                            AnamnesisId = 2,
                            Name = "Virus"
                        },
                        new
                        {
                            Id = 3,
                            AnamnesisId = 2,
                            Name = "Migrena"
                        });
                });

            modelBuilder.Entity("Model.PatientDoctor.MedicalRecord", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("AnamnesisId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnamnesisId");

                    b.ToTable("MedicalRecords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnamnesisId = 1,
                            PatientId = 1
                        },
                        new
                        {
                            Id = 2,
                            AnamnesisId = 1,
                            PatientId = 2
                        },
                        new
                        {
                            Id = 3,
                            AnamnesisId = 1,
                            PatientId = 3
                        },
                        new
                        {
                            Id = 4,
                            AnamnesisId = 1,
                            PatientId = 4
                        });
                });

            modelBuilder.Entity("Model.PatientDoctor.Symptoms", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AnamnesisId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("AnamnesisId");

                    b.ToTable("Symptomes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnamnesisId = 2,
                            Name = "Temperatura"
                        },
                        new
                        {
                            Id = 2,
                            AnamnesisId = 1,
                            Name = "Kašalj"
                        },
                        new
                        {
                            Id = 3,
                            AnamnesisId = 2,
                            Name = "Glavobolja"
                        });
                });

            modelBuilder.Entity("Model.Term.MedicalExamination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FromDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("ToDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Urgency")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.HasIndex("RoomId");

                    b.ToTable("MedicalExamination");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DoctorId = 1,
                            FromDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 2,
                            RoomId = 1,
                            ShortDescription = "Sve je bilo uredu na pregledu",
                            ToDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Urgency = false
                        },
                        new
                        {
                            Id = 2,
                            DoctorId = 2,
                            FromDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 1,
                            RoomId = 2,
                            ShortDescription = "Sve je bilo uredu na pregledu",
                            ToDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Urgency = false
                        },
                        new
                        {
                            Id = 3,
                            DoctorId = 2,
                            FromDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 3,
                            RoomId = 3,
                            ShortDescription = "Sve je bilo uredu na pregledu",
                            ToDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Urgency = false
                        });
                });

            modelBuilder.Entity("Model.Term.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("FromDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RoomId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("ToDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TypeOfRoomId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TypeOfRoomId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FromDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = "101",
                            ToDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeOfRoomId = 1
                        },
                        new
                        {
                            Id = 2,
                            FromDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = "201",
                            ToDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeOfRoomId = 1
                        },
                        new
                        {
                            Id = 3,
                            FromDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = "301",
                            ToDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeOfRoomId = 1
                        });
                });

            modelBuilder.Entity("Model.Term.Surgery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DoctorSpecialistId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FromDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("ToDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Urgency")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorSpecialistId");

                    b.HasIndex("PatientId");

                    b.HasIndex("RoomId");

                    b.ToTable("Survey");
                });

            modelBuilder.Entity("Model.Term.TypeOfRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NameOfType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("TypesOfRoom");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NameOfType = "Soba za preglede"
                        },
                        new
                        {
                            Id = 2,
                            NameOfType = "Soba za operacije"
                        });
                });

            modelBuilder.Entity("Backend.Model.BlogAndNotification.PatientFeedback", b =>
                {
                    b.HasOne("Model.AllActors.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Model.PatientDoctor.MedicalExaminationReport", b =>
                {
                    b.HasOne("Model.Term.MedicalExamination", "MedicalExamination")
                        .WithMany()
                        .HasForeignKey("MedicalExaminationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Model.AllActors.City", b =>
                {
                    b.HasOne("Model.AllActors.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Model.AllActors.Doctor", b =>
                {
                    b.HasOne("Model.Doctor.Specialitation", "Specialitation")
                        .WithMany()
                        .HasForeignKey("SpecialitationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Model.DoctorMenager.Medicament", b =>
                {
                    b.HasOne("Model.PatientDoctor.MedicalRecord", "MedicalRecord")
                        .WithMany("Medicament")
                        .HasForeignKey("MedicalRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Model.Manager.InventaryRoom", b =>
                {
                    b.HasOne("Model.Term.Room", "Room")
                        .WithMany("Equipment")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Model.Patient.Question", b =>
                {
                    b.HasOne("Model.Patient.Survey", "Survey")
                        .WithMany("Questions")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Model.Patient.Survey", b =>
                {
                    b.HasOne("Model.Term.MedicalExamination", "MedicalExamination")
                        .WithMany()
                        .HasForeignKey("MedicalExaminationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Model.PatientDoctor.Allergies", b =>
                {
                    b.HasOne("Model.PatientDoctor.MedicalRecord", "MedicalRecord")
                        .WithMany("Allergies")
                        .HasForeignKey("MedicalRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Model.PatientDoctor.Diagnosis", b =>
                {
                    b.HasOne("Model.PatientDoctor.Anamnesis", "Anamnesis")
                        .WithMany("Diagnosis")
                        .HasForeignKey("AnamnesisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Model.PatientDoctor.MedicalRecord", b =>
                {
                    b.HasOne("Model.PatientDoctor.Anamnesis", "Anamnesis")
                        .WithMany()
                        .HasForeignKey("AnamnesisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.AllActors.Patient", "Patient")
                        .WithOne("MedicalRecord")
                        .HasForeignKey("Model.PatientDoctor.MedicalRecord", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Model.PatientDoctor.Symptoms", b =>
                {
                    b.HasOne("Model.PatientDoctor.Anamnesis", "Anamnesis")
                        .WithMany("Symptoms")
                        .HasForeignKey("AnamnesisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Model.Term.MedicalExamination", b =>
                {
                    b.HasOne("Model.AllActors.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.AllActors.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Term.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Model.Term.Room", b =>
                {
                    b.HasOne("Model.Term.TypeOfRoom", "TypeOfRoom")
                        .WithMany()
                        .HasForeignKey("TypeOfRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Model.Term.Surgery", b =>
                {
                    b.HasOne("Model.AllActors.Doctor", "DoctorSpecialist")
                        .WithMany()
                        .HasForeignKey("DoctorSpecialistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.AllActors.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Term.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
