version: "3.8"

services:
  appointments:
    build: 
      context: .
      dockerfile: AppointmentMicroservice/Dockerfile
    image: astevanovic/appointments:latest
    restart: on-failure
    environment:
      DATABASE_USERNAME: b3d96cd31e111f
      DATABASE_PASSWORD: 093b1653
      DATABASE_HOST: eu-cdbr-west-03.cleardb.net
      DATABASE_SCHEMA: heroku_2eb25381370a0b7
      DATABASE_SCHEMA_EVENT: heroku_2eb25381370a0b7
      USERS_URL: care-cure-users.herokuapp.com
      USERS_PORT: "80"
    expose: 
      - "80"
    ports:
      - "6002:80"
    networks:
      - public_net
  documents:
    build: 
      context: .
      dockerfile: DocumentsMicroservice/Dockerfile
    image:  astevanovic/documents:latest
    restart: on-failure
    environment:
      DATABASE_USERNAME: b3d96cd31e111f
      DATABASE_PASSWORD: 093b1653
      DATABASE_HOST: eu-cdbr-west-03.cleardb.net
      DATABASE_SCHEMA: heroku_2eb25381370a0b7
      DATABASE_SCHEMA_EVENT: heroku_2eb25381370a0b7
      USERS_URL: care-cure-users.herokuapp.com
      USERS_PORT: "80"
      APPO_URL: care-cure-appointments.herokuapp.com
      APPO_PORT: "80"
    expose: 
      - "80"
    ports:
      - "6003:80"
    networks:
      - public_net
  feedbacks:
    build: 
      context: .
      dockerfile: FeedbackMicroservice/Dockerfile
    image:  astevanovic/feedbacks:latest
    restart: on-failure
    environment:
      DATABASE_USERNAME: b3d96cd31e111f
      DATABASE_PASSWORD: 093b1653
      DATABASE_HOST: eu-cdbr-west-03.cleardb.net
      DATABASE_SCHEMA: heroku_2eb25381370a0b7
      DATABASE_SCHEMA_EVENT: heroku_2eb25381370a0b7
      USERS_URL: care-cure-users.herokuapp.com
      USERS_PORT: "80"
      APPO_URL: care-cure-appointments.herokuapp.com
      APPO_PORT: "80"
    expose: 
      - "80"
    ports:
      - "6004:80"
    networks:
      - public_net
  users:
    build: 
      context: .
      dockerfile: UserMicroservice/Dockerfile
    image:  astevanovic/users:latest
    restart: on-failure
    environment:
      DATABASE_USERNAME: b3d96cd31e111f
      DATABASE_PASSWORD: 093b1653
      DATABASE_HOST: eu-cdbr-west-03.cleardb.net
      DATABASE_SCHEMA: heroku_2eb25381370a0b7
      DATABASE_SCHEMA_EVENT: heroku_2eb25381370a0b7
      APPO_URL: care-cure-appointments.herokuapp.com
      APPO_PORT: "80"
    expose: 
      - "80"
    ports:
      - "6005:80"
    networks:
      - public_net
  gateway:
    build:
      context: .
      dockerfile: GatewayWebApi/Dockerfile
    image:  astevanovic/gateway:latest
    restart: on-failure
    environment:
      PURPOSE: prod 
    depends_on:
      - appointments
      - documents
      - feedbacks
      - users
    expose: 
      - "80"
    ports:
      - "6006:80"
    networks:
      - public_net
networks:
  public_net:
    driver: bridge
