version: "3.8"

services:
  mysql:
    image: mysql:5.6
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: HealthClinicDB
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql-db:/var/lib/mysql
      - ./TestScripts:/docker-entrypoint-initdb.d/
    networks:
      - public_net
  appointment:
    build: 
      context: .
      dockerfile: AppointmentMicroservice/Dockerfile
    image: astevanovic/appointment:latest
    restart: on-failure
    environment:
      DATABASE_USERNAME: user
      DATABASE_PASSWORD: user
      DATABASE_HOST: mysql
      DATABASE_SCHEMA: HealthClinicDB
      DATABASE_SCHEMA_EVENT: EventSourcingDB
      USERS_URL: users
      USERS_PORT: "80"
      SHOW_ENV: 'TRUE'
    depends_on:
      - mysql
    expose: 
      - "80"
    ports:
      - "6002:80"
    networks:
      - public_net
  documents:
    build: 
      context: .
      dockerfile: DocumentsMicroservice/Dockerfile
    image: astevanovic/documents:latest
    restart: on-failure
    environment:
      DATABASE_USERNAME: user
      DATABASE_PASSWORD: user
      DATABASE_HOST: mysql
      DATABASE_SCHEMA: HealthClinicDB
      DATABASE_SCHEMA_EVENT: EventSourcingDB
      APPO_URL: appointment
      APPO_PORT: "80"
      USERS_URL: users
      USERS_PORT: "80"
      SHOW_ENV: 'TRUE'
    depends_on:
      - mysql
    expose: 
      - "80"
    ports:
      - "6003:80"
    networks:
      - public_net
  feedbacks:
    build: 
      context: .
      dockerfile: FeedbackMicroservice/Dockerfile
    image: astevanovic/feedbacks:latest
    restart: on-failure
    environment:
      DATABASE_USERNAME: user
      DATABASE_PASSWORD: user
      DATABASE_HOST: mysql
      DATABASE_SCHEMA: HealthClinicDB
      DATABASE_SCHEMA_EVENT: EventSourcingDB
      APPO_URL: appointment
      APPO_PORT: "80"
      USERS_URL: users
      USERS_PORT: "80"
      SHOW_ENV: 'TRUE'
    depends_on:
      - mysql
    expose: 
      - "80"
    ports:
      - "6004:80"
    networks:
      - public_net
  users:
    build: 
      context: .
      dockerfile: UserMicroservice/Dockerfile
    image: astevanovic/users:latest
    restart: on-failure
    environment:
      DATABASE_USERNAME: user
      DATABASE_PASSWORD: user
      DATABASE_HOST: mysql
      DATABASE_SCHEMA: HealthClinicDB
      DATABASE_SCHEMA_EVENT: EventSourcingDB
      APPO_URL: appointment
      APPO_PORT: "80"
      SHOW_ENV: 'TRUE'
    depends_on:
      - mysql
    expose: 
      - "80"
    ports:
      - "6005:80"
    networks:
      - public_net
  gateway:
    build:
      context: .
      dockerfile: GatewayWebApi/Dockerfile
    image: astevanovic/gateway:latest
    restart: on-failure
    environment:
      PURPOSE: dep 
    depends_on:
      - appointment
      - documents
      - feedbacks
      - users
    expose: 
      - "80"
    ports:
      - "6006:80"
    networks:
      - public_net
networks:
  public_net:
    driver: bridge
volumes:
  mysql-db: